"""initial migration

Revision ID: 30b3c3f0ccd5
Revises: c1eab0616214
Create Date: 2020-08-12 21:34:34.404815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b3c3f0ccd5'
down_revision = 'c1eab0616214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('class_name', sa.String(length=12), nullable=True),
    sa.Column('intention', sa.String(length=12), nullable=True),
    sa.Column('qq', sa.String(length=24), nullable=True),
    sa.Column('major', sa.String(length=24), nullable=True),
    sa.Column('phone_num', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('office', sa.String(length=64), nullable=True),
    sa.Column('software', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('cognition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_num'),
    sa.UniqueConstraint('qq')
    )
    op.create_index(op.f('ix_applicant_id'), 'applicant', ['id'], unique=False)
    op.create_index(op.f('ix_applicant_intention'), 'applicant', ['intention'], unique=False)
    op.create_index(op.f('ix_applicant_name'), 'applicant', ['name'], unique=True)
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_index(op.f('ix_applicant_name'), table_name='applicant')
    op.drop_index(op.f('ix_applicant_intention'), table_name='applicant')
    op.drop_index(op.f('ix_applicant_id'), table_name='applicant')
    op.drop_table('applicant')
    # ### end Alembic commands ###
