"""initial migration

Revision ID: 5b3d35661c1d
Revises: 3649a97e4319
Create Date: 2020-07-22 12:54:37.518552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3d35661c1d'
down_revision = '3649a97e4319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('student_num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_class_name'), 'users', ['class_name'], unique=True)
    op.create_index(op.f('ix_users_student_num'), 'users', ['student_num'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_student_num'), table_name='users')
    op.drop_index(op.f('ix_users_class_name'), table_name='users')
    op.drop_column('users', 'student_num')
    op.drop_column('users', 'class_name')
    # ### end Alembic commands ###
