"""initial migration

Revision ID: 9f31002244c8
Revises: 5b3d35661c1d
Create Date: 2020-07-22 15:10:45.898665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f31002244c8'
down_revision = '5b3d35661c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_college'), 'users', ['college'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_college'), table_name='users')
    op.drop_column('users', 'college')
    # ### end Alembic commands ###
